---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: hub.lab.example.com/ee-supported-rhel8:latest
  EE_BUILDER_IMAGE: hub.lab.example.com/ansible-builder-rhel8:latest


dependencies:
 galaxy: requirements.yml
 python: requirements.txt
 system: bindep.txt 
